//go:generate goderive
package utils

import (
	"io"
	"unicode"

	"github.com/olekukonko/tablewriter"
)

func Capitalize(s string) string {
	if len(s) == 0 {
		return s
	}
	if 'a' <= s[0] && s[0] <= 'z' {
		b := []byte(s)
		b[0] = b[0] - (byte('a') - 'A')
		return string(b)
	}
	return s
}

type TableWriter struct {
	table *tablewriter.Table
}

func NewTableWriter(w io.Writer) *TableWriter {
	t := tablewriter.NewWriter(w)
	t.SetColWidth(60)
	t.SetBorders(tablewriter.Border{Left: false, Right: false, Top: false, Bottom: false})
	t.SetHeaderLine(false)
	t.SetColumnSeparator("\t")
	t.SetAlignment(tablewriter.ALIGN_LEFT)
	return &TableWriter{table: t}
}

func (tw *TableWriter) Append(row []string) {
	tw.table.Append(row)
}

func (tw *TableWriter) Render() {
	tw.table.Render()
}

// derive-set: Order=Append
type Str = string

// derive-set: Rename=StrOrderSet;Order=Key
type Str2 = string

const HeaderComment = "// Code generated by https://github.com/nextzhou/goderive. DO NOT EDIT.\n\n"

func ToExported(ident string) string {
	if len(ident) == 0 {
		return ident
	}
	return string(unicode.ToUpper(rune(ident[0]))) + ident[1:]
}

func ToUnexported(ident string) string {
	if len(ident) == 0 {
		return ident
	}
	return string(unicode.ToLower(rune(ident[0]))) + ident[1:]
}
